### ISSUE TITLE
Question: does pyzstd allow inherited class?

### ISSUE THREAD

**Issue by miurahr** [animalize/pyzstd#2]
When using pyzstd in following style;

```
class ZstdDecompressor(pyzstd.ZstdDecompressor):
 
     def __init__(self, properties):
         if (properties[0], properties[1], 0) > ZSTD_VERSION:
             raise Exception("Version error")
        super.__init__()
```

It leads `TypeError: type '_zstd.ZstdDecompressor' is not an acceptable base type`.
I've tested with pyzstd==0.14.1

A following alternative is working well.
```
class ZstdDecompressor:
 
     def __init__(self, properties):
         if (properties[0], properties[1], 0) > ZSTD_VERSION:
             raise Exception("Version error")
        self.decompressor = pyzstd.ZstdDecompressor()

    def decompress(self, data):
        return self.decompressor.decompress(data)
```

**Comment by animalize** [comment]
This module was written for CPython stdlib, it used to use [Multi-phase extension module initialization](https://www.python.org/dev/peps/pep-0489/).
Then the code needed to get module state using `PyType_GetModuleState()` function, which is not safe calling on a subclass.

Since `pyzstd` no longer uses "Multi-phase extension module initialization", this restriction can be removed, just add `Py_TPFLAGS_BASETYPE` flag to here:

```c
static PyType_Spec ZstdDecompressor_type_spec = {
    .name = "_zstd.ZstdDecompressor",
    .basicsize = sizeof(ZstdDecompressor),
    /* Calling PyType_GetModuleState() on a subclass is not safe.
       ZstdDecompressor_type_spec does not have Py_TPFLAGS_BASETYPE flag
       which prevents to create a subclass.
       So calling PyType_GetModuleState() in this file is always safe. */
    .flags = Py_TPFLAGS_DEFAULT,
    .slots = ZstdDecompressor_slots,
};
```

FYI, in CPython 3.10, can't create a subclass of `LZMADecompressor` class for this reason.
https://github.com/python/cpython/commit/1937edd376274cb26090d71253191502a9de32d6#diff-604739065f6d9a2f56bed1e9d1fd56b51e212e9acd630a92ccac9fe8390fa4d9

**Comment by animalize** [comment]
The 0.14.2 removed this restriction.

**Comment by miurahr** [comment]
Thank you for explanation.
